<?php
/**
 * ApiProjectsPost400Response
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  App\Http\Requests
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Task Management API
 *
 * タスク管理・工数管理システムのAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Http\Requests\Requests;

use \ArrayAccess;
use \App\Http\Requests\ObjectSerializer;

/**
 * ApiProjectsPost400Response Class Doc Comment
 *
 * @category Class
 * @package  App\Http\Requests
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * ApiProjectsPost400Response
 */
class ApiProjectsPost400Response extends FormRequest
{
    /**
     * このリクエストの認可ロジック
     */
    public function authorize(): bool
    {
        // 必要に応じて認可ロジックを実装
        return true;
    }

    /**
     * バリデーションルール
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'message' => ['required', 'string'],
            'errors' => ['required'],
        ];
    }

    /**
     * バリデーションエラーメッセージのカスタマイズ
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'message.required' => 'は必須です',
            'message.string' => 'は文字列である必要があります',
            'errors.required' => 'は必須です',
        ];
    }
}


