<?php
/**
 * ApiProjectsPost201Response
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  App\Http\Requests
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Task Management API
 *
 * タスク管理・工数管理システムのAPI仕様
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace App\Http\Requests\Requests;

use \ArrayAccess;
use \App\Http\Requests\ObjectSerializer;

/**
 * ApiProjectsPost201Response Class Doc Comment
 *
 * @category Class
 * @package  App\Http\Requests
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * ApiProjectsPost201Response
 */
class ApiProjectsPost201Response extends FormRequest
{
    /**
     * このリクエストの認可ロジック
     */
    public function authorize(): bool
    {
        // 必要に応じて認可ロジックを実装
        return true;
    }

    /**
     * バリデーションルール
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'id' => ['required', 'numeric'],
            'name' => ['required', 'string'],
            'amount' => ['required', 'numeric'],
            'description' => ['required', 'string'],
            'started_at' => ['required', 'string'],
            'ended_at' => ['required', 'string'],
            'is_active' => ['required', 'boolean'],
            'created_at' => ['required', 'string'],
            'updated_at' => ['required', 'string'],
        ];
    }

    /**
     * バリデーションエラーメッセージのカスタマイズ
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'id.required' => 'は必須です',
            'id.numeric' => 'は数値である必要があります',
            'name.required' => 'は必須です',
            'name.string' => 'は文字列である必要があります',
            'amount.required' => 'は必須です',
            'amount.numeric' => 'は数値である必要があります',
            'description.required' => 'は必須です',
            'description.string' => 'は文字列である必要があります',
            'started_at.required' => 'は必須です',
            'started_at.string' => 'は文字列である必要があります',
            'ended_at.required' => 'は必須です',
            'ended_at.string' => 'は文字列である必要があります',
            'is_active.required' => 'は必須です',
            'created_at.required' => 'は必須です',
            'created_at.string' => 'は文字列である必要があります',
            'updated_at.required' => 'は必須です',
            'updated_at.string' => 'は文字列である必要があります',
        ];
    }
}


